CREATE TABLE IF NOT EXISTS users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email varchar(190) NOT NULL UNIQUE,
  email_verified_at timestamptz,
  password_hash varchar(255) NOT NULL,
  last_login_at timestamptz,
  role text NOT NULL DEFAULT 'buyer' CHECK (role IN ('buyer','org_member','org_admin','platform_admin')),
  leaderboard_opt_in boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS sessions (
  id varchar(128) PRIMARY KEY,
  user_id bigint REFERENCES users(id) ON DELETE CASCADE,
  csrf_token varchar(128) NOT NULL,
  data jsonb NOT NULL DEFAULT '{}'::jsonb,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS sessions_expiry_idx ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS auth_tokens (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  purpose text NOT NULL CHECK (purpose IN ('email_verification','password_reset')),
  token_hash char(64) NOT NULL UNIQUE,
  expires_at timestamptz NOT NULL,
  consumed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS auth_rate_limits (
  bucket_hash char(64) NOT NULL,
  action varchar(40) NOT NULL,
  attempts smallint NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  window_started_at timestamptz NOT NULL DEFAULT now(),
  blocked_until timestamptz,
  updated_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY(bucket_hash,action)
);

CREATE TABLE IF NOT EXISTS organizations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL CHECK (type IN ('seed_bank','botanic_garden','nursery','shop','grower','collector')),
  name varchar(190) NOT NULL,
  slug varchar(190) NOT NULL UNIQUE,
  country varchar(100) NOT NULL,
  country_code char(2),
  region varchar(190),
  description text NOT NULL,
  specialties text,
  contact_url varchar(500),
  website_url varchar(500),
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected','info_requested')),
  seller_status text NOT NULL DEFAULT 'not_requested' CHECK (seller_status IN ('not_requested','onboarding','pending_review','active','suspended')),
  marketplace_enabled boolean NOT NULL DEFAULT false,
  stripe_account_id varchar(190) UNIQUE,
  stripe_charges_enabled boolean NOT NULL DEFAULT false,
  stripe_payouts_enabled boolean NOT NULL DEFAULT false,
  commission_bps integer NOT NULL DEFAULT 1000 CHECK (commission_bps BETWEEN 0 AND 5000),
  payout_policy text NOT NULL DEFAULT 'standard' CHECK (payout_policy IN ('standard','delivery_protected')),
  verified_at timestamptz,
  profile_updated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS organization_members (
  organization_id bigint NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role text NOT NULL DEFAULT 'member' CHECK (role IN ('member','admin')),
  PRIMARY KEY(organization_id,user_id)
);

CREATE TABLE IF NOT EXISTS founder_program_state (
  id smallint PRIMARY KEY CHECK (id = 1),
  current_slot smallint NOT NULL DEFAULT 0 CHECK (current_slot BETWEEN 0 AND 50),
  updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO founder_program_state(id,current_slot) VALUES(1,0) ON CONFLICT(id) DO NOTHING;

CREATE TABLE IF NOT EXISTS founder_program_members (
  organization_id bigint PRIMARY KEY REFERENCES organizations(id),
  slot_number smallint NOT NULL UNIQUE CHECK (slot_number BETWEEN 1 AND 50),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','rate_expired','revoked')),
  awarded_at timestamptz NOT NULL DEFAULT now(),
  marketplace_activated_at timestamptz,
  rate_expires_at timestamptz,
  revoked_at timestamptz,
  revoked_by_user_id bigint REFERENCES users(id),
  founder_commission_bps integer NOT NULL DEFAULT 700 CHECK (founder_commission_bps BETWEEN 0 AND 5000)
);

CREATE TABLE IF NOT EXISTS media_assets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint REFERENCES organizations(id),
  uploaded_by_user_id bigint REFERENCES users(id),
  kind text NOT NULL CHECK (kind IN ('organization_logo','organization_cover','product_image','collection_image')),
  origin text NOT NULL DEFAULT 'uploaded' CHECK (origin IN ('uploaded','curated','system')),
  source_url varchar(1000), is_active boolean NOT NULL DEFAULT true,
  storage_key varchar(190) NOT NULL UNIQUE,
  mime_type text NOT NULL CHECK (mime_type IN ('image/jpeg','image/png','image/webp')),
  byte_size integer NOT NULL CHECK (byte_size > 0),
  width_px integer NOT NULL CHECK (width_px BETWEEN 1 AND 6000),
  height_px integer NOT NULL CHECK (height_px BETWEEN 1 AND 6000),
  sha256 char(64), created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id bigint NOT NULL REFERENCES organizations(id),
  external_source varchar(80), external_id varchar(190), source_updated_at timestamptz,
  source_sync_status text NOT NULL DEFAULT 'manual' CHECK (source_sync_status IN ('manual','current','stale','error','review_required')),
  purchase_mode text NOT NULL DEFAULT 'marketplace' CHECK (purchase_mode IN ('marketplace','external')),
  external_purchase_url varchar(1000), sku varchar(100) NOT NULL UNIQUE,
  name varchar(255) NOT NULL, botanical_name varchar(255), slug varchar(190) NOT NULL UNIQUE, category varchar(100),
  description text NOT NULL, origin_country varchar(100), packet_quantity varchar(120), germination_notes text, hardiness_zone varchar(80),
  price_cents bigint NOT NULL CHECK (price_cents >= 0), compare_at_price_cents bigint CHECK (compare_at_price_cents >= 0),
  currency char(3) NOT NULL DEFAULT 'EUR', stock_quantity integer NOT NULL DEFAULT 0 CHECK (stock_quantity >= 0),
  image_url varchar(1000), primary_media_id bigint REFERENCES media_assets(id),
  compliance_flag text NOT NULL DEFAULT 'none' CHECK (compliance_flag IN ('none','phytosanitary_required','restricted')),
  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','pending_review','active','rejected','sold_out','withdrawn')),
  publication_batch_id bigint, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(organization_id,external_source,external_id)
);
CREATE INDEX IF NOT EXISTS products_public_idx ON products(status,category,organization_id);

CREATE TABLE IF NOT EXISTS seller_shipping_zones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organizations(id),
  name varchar(120) NOT NULL, countries text NOT NULL, rate_cents bigint NOT NULL CHECK (rate_cents >= 0),
  currency char(3) NOT NULL DEFAULT 'EUR', active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS exchange_listings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organizations(id),
  title varchar(255) NOT NULL, species varchar(255), variety varchar(255), category varchar(100), origin_country varchar(100),
  quantity_available varchar(120), wants text, contact_url varchar(500), description text NOT NULL,
  mode text NOT NULL DEFAULT 'exchange' CHECK (mode IN ('exchange','donate')),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','completed','withdrawn')),
  completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint REFERENCES users(id), email varchar(190) NOT NULL,
  status text NOT NULL DEFAULT 'pending_payment' CHECK (status IN ('pending_payment','processing_payment','paid','partially_fulfilled','fulfilled','cancelled','partially_refunded','refunded','disputed')),
  subtotal_cents bigint NOT NULL CHECK (subtotal_cents >= 0), shipping_cents bigint NOT NULL CHECK (shipping_cents >= 0),
  total_cents bigint NOT NULL CHECK (total_cents >= 0), currency char(3) NOT NULL DEFAULT 'EUR', shipping_country varchar(100) NOT NULL,
  shipping_name varchar(190), shipping_line1 varchar(255), shipping_line2 varchar(255), shipping_city varchar(190), shipping_state varchar(190),
  shipping_postal_code varchar(40), shipping_phone varchar(60),
  shipping_address_status text NOT NULL DEFAULT 'pending' CHECK (shipping_address_status IN ('pending','collected','invalid')),
  stripe_checkout_session_id varchar(190) UNIQUE, stripe_payment_intent_id varchar(190) UNIQUE, stripe_charge_id varchar(190) UNIQUE,
  transfer_group varchar(120) UNIQUE, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seller_orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint NOT NULL REFERENCES orders(id),
  organization_id bigint NOT NULL REFERENCES organizations(id),
  status text NOT NULL DEFAULT 'pending_payment' CHECK (status IN ('pending_payment','paid','processing','shipped','delivered','cancelled','refunded','disputed')),
  subtotal_cents bigint NOT NULL, shipping_cents bigint NOT NULL, commission_bps integer NOT NULL,
  commission_cents bigint NOT NULL, seller_net_cents bigint NOT NULL, currency char(3) NOT NULL DEFAULT 'EUR',
  payout_policy text NOT NULL CHECK (payout_policy IN ('standard','delivery_protected')),
  transfer_status text NOT NULL DEFAULT 'pending' CHECK (transfer_status IN ('pending','held','eligible','processing','paid','failed','reversed')),
  stripe_transfer_id varchar(190) UNIQUE, carrier varchar(120), tracking_number varchar(190), tracking_url varchar(500),
  shipped_at timestamptz, delivery_due_at timestamptz, delivered_at timestamptz, transfer_eligible_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(order_id,organization_id)
);

CREATE TABLE IF NOT EXISTS order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint NOT NULL REFERENCES orders(id),
  seller_order_id bigint REFERENCES seller_orders(id), organization_id bigint REFERENCES organizations(id),
  product_id bigint NOT NULL REFERENCES products(id), sku varchar(100) NOT NULL, name varchar(255) NOT NULL,
  unit_price_cents bigint NOT NULL CHECK (unit_price_cents >= 0), quantity integer NOT NULL CHECK (quantity > 0)
);

CREATE TABLE IF NOT EXISTS inventory_reservations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id bigint NOT NULL REFERENCES orders(id),
  product_id bigint NOT NULL REFERENCES products(id), quantity integer NOT NULL CHECK (quantity > 0),
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active','converted','released')),
  expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(order_id,product_id)
);

CREATE TABLE IF NOT EXISTS stripe_events (
  stripe_event_id varchar(190) PRIMARY KEY, event_type varchar(120) NOT NULL, payload_hash char(64),
  status text NOT NULL DEFAULT 'processed' CHECK (status IN ('processing','processed','failed')),
  last_error varchar(500), processed_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS seller_transfers (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, seller_order_id bigint NOT NULL UNIQUE REFERENCES seller_orders(id),
  organization_id bigint NOT NULL REFERENCES organizations(id), amount_cents bigint NOT NULL CHECK (amount_cents >= 0),
  currency char(3) NOT NULL DEFAULT 'EUR', status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','paid','failed','reversed')),
  stripe_transfer_id varchar(190) UNIQUE, attempts smallint NOT NULL DEFAULT 0, last_error varchar(500),
  processed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS delivery_cases (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, seller_order_id bigint NOT NULL REFERENCES seller_orders(id),
  opened_by_user_id bigint NOT NULL REFERENCES users(id), reason text NOT NULL CHECK (reason IN ('not_received','damaged','wrong_item','other')),
  details text NOT NULL, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewing','resolved_release','resolved_refund','closed')),
  resolution_notes text, resolved_by_user_id bigint REFERENCES users(id), resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS favorites (
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE, product_id bigint NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,product_id)
);

CREATE TABLE IF NOT EXISTS collection_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), product_id bigint REFERENCES products(id),
  source_organization_id bigint REFERENCES organizations(id), species_name varchar(255) NOT NULL,
  status text NOT NULL DEFAULT 'waiting' CHECK (status IN ('waiting','planted','growing','failed')),
  acquired_at date, planted_at date, germinated_at date, notes text,
  visibility text NOT NULL DEFAULT 'private' CHECK (visibility IN ('private','public')),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS growth_journal_entries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, collection_item_id bigint NOT NULL REFERENCES collection_items(id),
  user_id bigint NOT NULL REFERENCES users(id), event_type text NOT NULL CHECK (event_type IN ('note','planted','germination','growth','failure')),
  note text NOT NULL, event_date date NOT NULL, media_asset_id bigint REFERENCES media_assets(id), created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, seller_order_id bigint NOT NULL REFERENCES seller_orders(id),
  user_id bigint NOT NULL REFERENCES users(id), organization_id bigint NOT NULL REFERENCES organizations(id), product_id bigint REFERENCES products(id),
  rating smallint NOT NULL CHECK (rating BETWEEN 1 AND 5), body text NOT NULL,
  status text NOT NULL DEFAULT 'published' CHECK (status IN ('published','hidden','reported')),
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(seller_order_id,user_id)
);

CREATE TABLE IF NOT EXISTS review_responses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, review_id bigint NOT NULL UNIQUE REFERENCES reviews(id),
  organization_id bigint NOT NULL REFERENCES organizations(id), responded_by_user_id bigint NOT NULL REFERENCES users(id),
  body text NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS conversations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organizations(id),
  buyer_user_id bigint NOT NULL REFERENCES users(id), archived_by_buyer boolean NOT NULL DEFAULT false,
  archived_by_organization boolean NOT NULL DEFAULT false, buyer_blocked_at timestamptz, organization_blocked_at timestamptz,
  last_message_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE(buyer_user_id,organization_id)
);

CREATE TABLE IF NOT EXISTS conversation_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, conversation_id bigint NOT NULL REFERENCES conversations(id),
  sender_user_id bigint NOT NULL REFERENCES users(id), body text NOT NULL, read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, reporter_user_id bigint NOT NULL REFERENCES users(id),
  entity_type text NOT NULL CHECK (entity_type IN ('organization','product','exchange','review','message')),
  entity_id bigint NOT NULL, reason text NOT NULL CHECK (reason IN ('fraud','misleading','restricted','abuse','other')),
  details text NOT NULL, status text NOT NULL DEFAULT 'open' CHECK (status IN ('open','reviewing','resolved','dismissed')),
  resolved_by_user_id bigint REFERENCES users(id), resolved_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), type varchar(80) NOT NULL,
  title varchar(190) NOT NULL, body text NOT NULL, action_url varchar(500), read_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS point_ledger (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id bigint NOT NULL REFERENCES users(id), event_key varchar(190) NOT NULL UNIQUE,
  event_type varchar(80) NOT NULL, points integer NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS achievement_unlocks (
  user_id bigint NOT NULL REFERENCES users(id), achievement_key varchar(120) NOT NULL,
  unlocked_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(user_id,achievement_key)
);

CREATE TABLE IF NOT EXISTS organization_channels (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organizations(id),
  channel_type text NOT NULL CHECK (channel_type IN ('email','whatsapp','telegram','facebook','instagram','pinterest','youtube','tiktok','amazon','ebay')),
  label varchar(120) NOT NULL, url varchar(1000) NOT NULL, is_verified boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(organization_id,channel_type)
);

CREATE TABLE IF NOT EXISTS supplier_catalog_imports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organizations(id), source varchar(80) NOT NULL,
  status text NOT NULL DEFAULT 'running' CHECK (status IN ('running','succeeded','completed_with_errors','failed')),
  accepted_count integer NOT NULL DEFAULT 0, rejected_count integer NOT NULL DEFAULT 0, stale_count integer NOT NULL DEFAULT 0,
  report jsonb, started_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
);

CREATE TABLE IF NOT EXISTS supplier_catalog_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organizations(id), source varchar(80) NOT NULL,
  external_id varchar(190) NOT NULL, item_group_id varchar(190), sku varchar(100) NOT NULL, name varchar(255) NOT NULL,
  description text NOT NULL, category varchar(100) NOT NULL, source_category varchar(255), botanical_name varchar(255),
  price_cents bigint NOT NULL, compare_at_price_cents bigint, currency char(3) NOT NULL, stock_quantity integer NOT NULL,
  packet_quantity varchar(120), origin_country varchar(100), compliance_flag text NOT NULL DEFAULT 'none', image_urls jsonb,
  external_purchase_url varchar(1000), source_updated_at timestamptz,
  validation_status text NOT NULL DEFAULT 'ready' CHECK (validation_status IN ('ready','rejected','stale','imported','review_required')),
  validation_errors jsonb, payload jsonb NOT NULL, first_seen_at timestamptz NOT NULL DEFAULT now(), last_seen_at timestamptz NOT NULL DEFAULT now(),
  imported_product_id bigint REFERENCES products(id), UNIQUE(organization_id,source,external_id)
);

CREATE TABLE IF NOT EXISTS supplier_publication_batches (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id bigint NOT NULL REFERENCES organizations(id), source varchar(80) NOT NULL,
  batch_type text NOT NULL DEFAULT 'publication' CHECK (batch_type IN ('publication','content_review')),
  status text NOT NULL DEFAULT 'pending_review' CHECK (status IN ('pending_review','approved','rejected')),
  open_scope varchar(190) UNIQUE, item_count integer NOT NULL DEFAULT 0, error_count integer NOT NULL DEFAULT 0,
  snapshot_hash char(64) NOT NULL, report jsonb NOT NULL,
  sitemap_status text NOT NULL DEFAULT 'pending' CHECK (sitemap_status IN ('pending','current','failed')),
  sitemap_error varchar(500), sitemap_current_at timestamptz, created_by_user_id bigint REFERENCES users(id), approved_by_user_id bigint REFERENCES users(id),
  created_at timestamptz NOT NULL DEFAULT now(), reviewed_at timestamptz
);

CREATE TABLE IF NOT EXISTS supplier_publication_batch_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id bigint NOT NULL REFERENCES supplier_publication_batches(id) ON DELETE CASCADE,
  supplier_catalog_item_id bigint NOT NULL REFERENCES supplier_catalog_items(id), product_id bigint REFERENCES products(id),
  position integer NOT NULL CHECK (position > 0), action text NOT NULL DEFAULT 'create' CHECK (action IN ('create','update')),
  snapshot jsonb NOT NULL, snapshot_hash char(64) NOT NULL, validation_errors jsonb,
  created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(batch_id,supplier_catalog_item_id), UNIQUE(batch_id,position)
);
ALTER TABLE products ADD CONSTRAINT products_publication_batch_id_fkey FOREIGN KEY(publication_batch_id) REFERENCES supplier_publication_batches(id);

CREATE TABLE IF NOT EXISTS outbox_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, event_key varchar(190) NOT NULL UNIQUE, recipient varchar(190) NOT NULL,
  subject varchar(255) NOT NULL, body text NOT NULL,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','processing','sent','failed')),
  attempts smallint NOT NULL DEFAULT 0, next_attempt_at timestamptz, locked_at timestamptz, last_error varchar(500),
  sent_at timestamptz, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_user_id bigint REFERENCES users(id), entity_type varchar(80) NOT NULL,
  entity_id bigint NOT NULL, event_name varchar(120) NOT NULL, payload jsonb, created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS organizations_public_idx ON organizations(status,type,country_code);
CREATE INDEX IF NOT EXISTS exchange_public_idx ON exchange_listings(status,mode,category);
CREATE INDEX IF NOT EXISTS seller_orders_worker_idx ON seller_orders(transfer_status,transfer_eligible_at);
CREATE INDEX IF NOT EXISTS reservations_expiry_idx ON inventory_reservations(status,expires_at);
CREATE INDEX IF NOT EXISTS outbox_delivery_idx ON outbox_messages(status,next_attempt_at,created_at);
CREATE INDEX IF NOT EXISTS reports_queue_idx ON reports(status,created_at);
