CREATE TABLE IF NOT EXISTS shipping_zones (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country varchar(100) NOT NULL,
  country_code char(2),
  rate_cents bigint NOT NULL CHECK (rate_cents >= 0),
  currency char(3) NOT NULL DEFAULT 'EUR',
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS legacy_migration_runs (
  id uuid PRIMARY KEY,
  source_fingerprint char(64) NOT NULL,
  mode text NOT NULL CHECK (mode IN ('dry-run','import')),
  status text NOT NULL CHECK (status IN ('running','succeeded','failed')),
  source_inventory jsonb NOT NULL,
  imported_counts jsonb,
  verification_report jsonb,
  started_at timestamptz NOT NULL DEFAULT now(),
  completed_at timestamptz
);
